testsuite: Made the tests more portable.

diff --git a/testsuite/wanted-results/parallel-local7 b/testsuite/wanted-results/parallel-local7
--- a/testsuite/wanted-results/parallel-local7
+++ b/testsuite/wanted-results/parallel-local7
@@ -1,80 +1,80 @@
-echo '### tmux1.9'
-### tmux1.9
-  seq 000   100 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+echo '### tmux-1.9'
+### tmux-1.9
+  seq 000   100 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 100   200 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 100   200 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 200   300 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 200   300 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 300   400 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 300   400 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 400   500 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 400   500 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 500   600 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 500   600 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 600   700 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 600   700 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 700   800 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 700   800 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 800   900 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 800   900 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 900  1000 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 900  1000 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 1000 1006 | PARALLEL_TMUX=tmux1.9 par_tmux
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 1000 1006 | PARALLEL_TMUX=tmux-1.9 par_tmux
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-echo '### tmux1.9 fails'
-### tmux1.9 fails
-  echo 1007 | PARALLEL_TMUX=tmux1.9 par_tmux
+echo '### tmux-1.9 fails'
+### tmux-1.9 fails
+  echo 1007 | PARALLEL_TMUX=tmux-1.9 par_tmux
 parallel: Error: Command line too long (2023 >= 2023) at input 0: 1007
 255
-  echo 1008 | PARALLEL_TMUX=tmux1.9 par_tmux
+  echo 1008 | PARALLEL_TMUX=tmux-1.9 par_tmux
 parallel: Error: Command line too long (2025 >= 2023) at input 0: 1008
 255
-  echo 1009 | PARALLEL_TMUX=tmux1.9 par_tmux
+  echo 1009 | PARALLEL_TMUX=tmux-1.9 par_tmux
 parallel: Error: Command line too long (2027 >= 2023) at input 0: 1009
 255
-echo '### tmux1.8'
-### tmux1.8
-  seq   1  50 | PARALLEL_TMUX=tmux1.8 par_tmux
-See output with: tmux1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+echo '### tmux-1.8'
+### tmux-1.8
+  seq   1  50 | PARALLEL_TMUX=tmux-1.8 par_tmux
+See output with: tmux-1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq  51 100 | PARALLEL_TMUX=tmux1.8 par_tmux
-See output with: tmux1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq  51 100 | PARALLEL_TMUX=tmux-1.8 par_tmux
+See output with: tmux-1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-  seq 101 113 | PARALLEL_TMUX=tmux1.8 par_tmux
-See output with: tmux1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 101 113 | PARALLEL_TMUX=tmux-1.8 par_tmux
+See output with: tmux-1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-echo '### tmux1.8 fails'
-### tmux1.8 fails
-  echo 114 | PARALLEL_TMUX=tmux1.8 par_tmux
+echo '### tmux-1.8 fails'
+### tmux-1.8 fails
+  echo 114 | PARALLEL_TMUX=tmux-1.8 par_tmux
 parallel: Error: Command line too long (236 >= 236) at input 0: 114
 255
-  echo 115 | PARALLEL_TMUX=tmux1.8 par_tmux
+  echo 115 | PARALLEL_TMUX=tmux-1.8 par_tmux
 parallel: Error: Command line too long (238 >= 236) at input 0: 115
 255
-  echo 116 | PARALLEL_TMUX=tmux1.8 par_tmux
+  echo 116 | PARALLEL_TMUX=tmux-1.8 par_tmux
 parallel: Error: Command line too long (240 >= 236) at input 0: 116
 255
-echo '### tmux1.8 0..255 ascii'
-### tmux1.8 0..255 ascii
-perl -e 'print map { ($_, map { pack("c*",$_) } grep { $_>=1 && $_!=10 } $_-110..$_),"\n" } 0..255' |    PARALLEL_TMUX=tmux1.8 stdout parallel --tmux --timeout 3 echo | par_tmux_filter; echo $?
-See output with: tmux1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+echo '### tmux-1.8 0..255 ascii'
+### tmux-1.8 0..255 ascii
+perl -e 'print map { ($_, map { pack("c*",$_) } grep { $_>=1 && $_!=10 } $_-110..$_),"\n" } 0..255' |    PARALLEL_TMUX=tmux-1.8 stdout parallel --tmux --timeout 3 echo | par_tmux_filter; echo $?
+See output with: tmux-1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
-echo '### tmux1.9 0..255 ascii'
-### tmux1.9 0..255 ascii
-perl -e 'print map { ($_, map { pack("c*",$_) } grep { $_>=1 && $_!=10 } 0..$_),"\n" } 0..255' |    PARALLEL_TMUX=tmux1.9 stdout parallel --tmux --timeout 3 echo | par_tmux_filter; echo $?
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+echo '### tmux-1.9 0..255 ascii'
+### tmux-1.9 0..255 ascii
+perl -e 'print map { ($_, map { pack("c*",$_) } grep { $_>=1 && $_!=10 } 0..$_),"\n" } 0..255' |    PARALLEL_TMUX=tmux-1.9 stdout parallel --tmux --timeout 3 echo | par_tmux_filter; echo $?
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 0
 echo '### Test output ascii'
 ### Test output ascii
@@ -83,12 +83,12 @@ See output with: tmux -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 053c7e8e945ef7641fc63bc309ac069d  -
 echo '### Test critical lengths. Must not block'
 ### Test critical lengths. Must not block
-  seq 70 130  | PARALLEL_TMUX=tmux1.8 stdout parallel --tmux echo '{}{=$_="&"x$_=}' | par_tmux_filter
-See output with: tmux1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 70 130  | PARALLEL_TMUX=tmux-1.8 stdout parallel --tmux echo '{}{=$_="&"x$_=}' | par_tmux_filter
+See output with: tmux-1.8 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
 parallel: Error: Command line too long (236 >= 236) at input 0: 114
-  seq 70 130  | PARALLEL_TMUX=tmux1.9 stdout parallel --tmux echo '{}{=$_="&"x$_=}' | par_tmux_filter
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
-  seq 280 425 | PARALLEL_TMUX=tmux1.8 stdout parallel --tmux echo '{}{=$_="a"x$_=}' | par_tmux_filter
+  seq 70 130  | PARALLEL_TMUX=tmux-1.9 stdout parallel --tmux echo '{}{=$_="&"x$_=}' | par_tmux_filter
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 280 425 | PARALLEL_TMUX=tmux-1.8 stdout parallel --tmux echo '{}{=$_="a"x$_=}' | par_tmux_filter
 parallel: Error: Command line too long (288 >= 236) at input 0: 280
-  seq 280 425 | PARALLEL_TMUX=tmux1.9 stdout parallel --tmux echo '{}{=$_="a"x$_=}' | par_tmux_filter
-See output with: tmux1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
+  seq 280 425 | PARALLEL_TMUX=tmux-1.9 stdout parallel --tmux echo '{}{=$_="a"x$_=}' | par_tmux_filter
+See output with: tmux-1.9 -S /tmp/parallel-local7-tmpdir/tmsXXXXX attach
